[package]
name = "cpio"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.162"
log = "0.4.22"
normalize-path = "0.2.1"
walkdir = "2.5.0"

[dev-dependencies]
arbitrary = { version = "1.4.1", features = ["derive", "derive_arbitrary"] }
arbtest = "0.3.1"
cpio-test = { path = "cpio-test" }
tempfile = "3.14.0"

[workspace]
members = [".", "cli", "cpio-test"]
default-members = [".", "cli"]
